name: form_builder_multi_dropdown
description: A highly customizable multi-selection dropdown field for Flutter FormBuilder. Supports responsive layouts, custom chip displays, and easy validation.
version: 0.9.7
resolution: workspace
homepage: https://o7planning.github.io
repository: https://github.com/o7planning/form_builder_multi_dropdown

platforms:
  android:
  ios:
  linux:
  macos:
  web: # override pana detection!
  windows:

environment:
  sdk: ^3.7.2
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_form_builder: ^10.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
